version: "3"

services:
  entriesdb:
    image: mongo:5
    restart: always
    ports:
      - 27020:27017
    environment:
      MONGODB_DATABASE: jira-entries
    volumes:
      - ./mongo:/data/database
